---
abstract: 'A POE::Component::IRC plugin that finds URIs in channel traffic.'
author:
  - 'Chris Williams'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.84'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POE-Component-IRC-Plugin-URI-Find
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  POE: 1.004
  POE::Component::IRC: 5.07
  POE::Component::IRC::Plugin: 0
  URI::Find: 0.16
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bingos/poe-component-irc-plugin-uri-find.git
version: 1.08
