author: Chris Williams
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: POE-Component-IRC-Plugin-URI-Find
no_index:
  directory:
    - inc
    - t
requires:
  POE: 0.37
  POE::Component::IRC: 5.07
  URI::Find: 0.16
version: 1.00
